import React, { Component } from "react";
import logo from "./logo.svg";
import "./App.css";
import ProjectItem from "./ProjectItem";
import PropTypes from "prop-types";

import AboutMe from "./About";
import Intro from "./Intro";

const mastermindpic = require("./img/mastermind.png");
const drrobotpic = require("./img/DrRobot.png");

class App extends Component {
  render() {
    return (
      <div>
        <header />
        <Intro />
        <AboutMe />
        <ProjectItem
          title="Mastermind Game"
          description="I developed this game at Brainstation as part of our pair programming project, with my friend Erin Feldman.
          The idea of the game is to guess a sequence of random colors generated by the computer with limited feedback. We based the design on the
          the look of the original board."
          image={mastermindpic}
          challenges="This game was a lot of fun for us to create. By far and away the most challening part of this was getting the
          logic for the check correct as there was a variety of scenarios we had to cover. This app really helped my solidify my Javascript knowledge, particularly with
          regards to loops and coniditionals"
          website="https://mastermind-game.herokuapp.com/"
        />
        <ProjectItem
          right={true}
          title="Dr. Robot"
          description="I developed Dr. Robot as my final project at Brainstation. I wanted my final project to reflect on something I cared about
          and given my background in healthcare I thought this would be the best path. I was able to find a medical API, known as APIMedic, and centered
          my app around a UI. The user is brought through a questionnaire so that they maybe diagnosed based on their symptoms as well as what specialists they
          should see. Due to the nature of the app I thought it best not to deploy Dr. Robot as it dealt with health diagnoses."
          image={drrobotpic}
          challenges="This was the first large scale app that I built and designed from the ground up by myself. It was a very challening process but I enjoyed
          every minute of it. In the end I was able to gain a good understanding of app Full-Stack development, which has immensely helped me in my career  ."
        />
      </div>
    );
  }
}

export default App;
